### PR TITLE
Ensure that ex.run() produces a Send future

### LINKED ISSUE #49: After non-breaking v1.5.2 release some types suddenly became non-send
related to: https://github.com/PolyMeilex/rfd/issues/136

After update from 1.5.1 to 1.5.2 futures that use async-executor internally suddenly became non send, braking the build. Which is kinda surprising for a patch releases.

```
error: future cannot be sent between threads safely
   --> src/backend/xdg_desktop_portal.rs:43:9
    |
43  | /         Box::pin(async {
44  | |             OpenFileRequest::default()
45  | |                 .accept_label("Pick file")
46  | |                 .multiple(false)
...   |
59  | |                 .map(FileHandle::from)
60  | |         })
    | |__________^ future created by async block is not `Send`
    |
    = help: within `[async block@src/backend/xdg_desktop_portal.rs:43:18: 60:10]`, the trait `std::marker::Send` is not implemented for `*const async_executor::State`
note: future is not `Send` as this value is used across an await
   --> /home/poly/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.5.2/src/lib.rs:936:18
    |
889 |                 let mut old = with_waker(|waker| {
    |                     ------- has type `std::option::Option<async_executor::LocalQueue>` which is not `Send`
...
936 |                 .await
    |                  ^^^^^ await occurs here, with `mut old` maybe used later
937 |             }
    |             - `mut old` is later dropped here
    = note: required for the cast from `Pin<Box<[async block@src/backend/xdg_desktop_portal.rs:43:18: 60:10]>>` to `Pin<Box<(dyn futures_util::Future<Output = std::option::Option<FileHandle>> + std::marker::Send + 'static)>>`

error: future cannot be sent between threads safely
   --> src/backend/xdg_desktop_portal.rs:64:9
    |
64  | /         Box::pin(async {
65  | |             OpenFileRequest::default()
66  | |                 .accept_label("Pick file(s)")
67  | |                 .multiple(true)
...   |
85  | |                 })
86  | |         })
    | |__________^ future created by async block is not `Send`
    |
    = help: within `[async block@src/backend/xdg_desktop_portal.rs:64:18: 86:10]`, the trait `std::marker::Send` is not implemented for `*const async_executor::State`
note: future is not `Send` as this value is used across an await
   --> /home/poly/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.5.2/src/lib.rs:936:18
    |
889 |                 let mut old = with_waker(|waker| {
    |                     ------- has type `std::option::Option<async_executor::LocalQueue>` which is not `Send`
...
936 |                 .await
    |                  ^^^^^ await occurs here, with `mut old` maybe used later
937 |             }
    |             - `mut old` is later dropped here
    = note: required for the cast from `Pin<Box<[async block@src/backend/xdg_desktop_portal.rs:64:18: 86:10]>>` to `Pin<Box<(dyn futures_util::Future<Output = std::option::Option<Vec<FileHandle>>> + std::marker::Send + 'static)>>`

error: future cannot be sent between threads safely
   --> src/backend/xdg_desktop_portal.rs:109:9
    |
109 | /         Box::pin(async {
110 | |             OpenFileRequest::default()
111 | |                 .accept_label("Pick folder")
112 | |                 .multiple(false)
...   |
126 | |                 .map(FileHandle::from)
127 | |         })
    | |__________^ future created by async block is not `Send`
    |
    = help: within `[async block@src/backend/xdg_desktop_portal.rs:109:18: 127:10]`, the trait `std::marker::Send` is not implemented for `*const async_executor::State`
note: future is not `Send` as this value is used across an await
   --> /home/poly/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.5.2/src/lib.rs:936:18
    |
889 |                 let mut old = with_waker(|waker| {
    |                     ------- has type `std::option::Option<async_executor::LocalQueue>` which is not `Send`
...
936 |                 .await
    |                  ^^^^^ await occurs here, with `mut old` maybe used later
937 |             }
    |             - `mut old` is later dropped here
    = note: required for the cast from `Pin<Box<[async block@src/backend/xdg_desktop_portal.rs:109:18: 127:10]>>` to `Pin<Box<(dyn futures_util::Future<Output = std::option::Option<FileHandle>> + std::marker::Send + 'static)>>`

error: future cannot be sent between threads safely
   --> src/backend/xdg_desktop_portal.rs:131:9
    |
131 | /         Box::pin(async {
132 | |             OpenFileRequest::default()
133 | |                 .accept_label("Pick folders")
134 | |                 .multiple(true)
...   |
153 | |                 })
154 | |         })
    | |__________^ future created by async block is not `Send`
    |
    = help: within `[async block@src/backend/xdg_desktop_portal.rs:131:18: 154:10]`, the trait `std::marker::Send` is not implemented for `*const async_executor::State`
note: future is not `Send` as this value is used across an await
   --> /home/poly/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.5.2/src/lib.rs:936:18
    |
889 |                 let mut old = with_waker(|waker| {
    |                     ------- has type `std::option::Option<async_executor::LocalQueue>` which is not `Send`
...
936 |                 .await
    |                  ^^^^^ await occurs here, with `mut old` maybe used later
937 |             }
    |             - `mut old` is later dropped here
    = note: required for the cast from `Pin<Box<[async block@src/backend/xdg_desktop_portal.rs:131:18: 154:10]>>` to `Pin<Box<(dyn futures_util::Future<Output = std::option::Option<Vec<FileHandle>>> + std::marker::Send + 'static)>>`

error: future cannot be sent between threads safely
   --> src/backend/xdg_desktop_portal.rs:172:9
    |
172 | /         Box::pin(async move {
173 | |             SaveFileRequest::default()
174 | |                 .accept_label("Save")
175 | |                 .title(&*self.title.unwrap_or_else(|| "Save file".to_string()))
...   |
190 | |                 .map(FileHandle::from)
191 | |         })
    | |__________^ future created by async block is not `Send`
    |
    = help: within `[async block@src/backend/xdg_desktop_portal.rs:172:18: 191:10]`, the trait `std::marker::Send` is not implemented for `*const async_executor::State`
note: future is not `Send` as this value is used across an await
   --> /home/poly/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.5.2/src/lib.rs:936:18
    |
889 |                 let mut old = with_waker(|waker| {
    |                     ------- has type `std::option::Option<async_executor::LocalQueue>` which is not `Send`
...
936 |                 .await
    |                  ^^^^^ await occurs here, with `mut old` maybe used later
937 |             }
    |             - `mut old` is later dropped here
    = note: required for the cast from `Pin<Box<[async block@src/backend/xdg_desktop_portal.rs:172:18: 191:10]>>` to `Pin<Box<(dyn futures_util::Future<Output = std::option::Option<FileHandle>> + std::marker::Send + 'static)>>`

error: could not compile `rfd` (lib) due to 5 previous errors
```

### PR DESCRIPTION
**Pull request by notgull**
Closes #49 

notgull code after spending 5 minutes in production:

robot fallx299

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -1052,3 +1052,37 @@ fn with_waker<F: FnOnce(&Waker) -> R, R>(f: F) -> impl Future<Output = R> {
...
+    /// is_send::<LocalExecutor<'_>>(LocalExecutor::new());
+    /// is_sync::<LocalExecutor<'_>>(LocalExecutor::new());
+    ///
+    /// let ex = LocalExecutor::new();
+    /// is_send(ex.run(pending::<()>()));
+    /// is_sync(ex.run(pending::<()>()));
+    /// is_send(ex.tick());
+    /// is_sync(ex.tick());
+    /// ```
+    fn _negative_test() {}
```
Comment (taiki-e) [inline src/lib.rs:1087]: (I think we expect all of the is_*s here to fail, but actually even if just one of them fails, this will be marked as a compaile_fail.)

**Review by taiki-e — APPROVED** [review]
